### ISSUE TITLE
tailProcessStderrLog does not return a value

### ISSUE THREAD

**Issue by rabol** [ihor/SupervisorXMLRPC#7]
Hi

$this->api = new Api('127.0.0.1', 9001 ,'user','123'/* username, password */);
dd($this->api->tailProcessStderrLog('laravel-worker:laravel-worker_00',0,-1024));

gives 'null' as result, even if there is a log file

Using Supervisor 3.3.5, API v3.0

**Comment by rabol** [comment]
the problem is that there is no return value in the api.php

    public function readProcessStderrLog($name, $offset, $length)
    {
        $this->__call('readProcessStderrLog', [$name, $offset, $length]);
    }

same problem for many other functions

**Comment by ihor** [comment]
Thanks, for pointing that out. Fixed!
